### ISSUE TITLE
Wrong Result

### ISSUE THREAD

**Issue by bemadlive** [adpth/BMI-Calculator#3]
App user interface good but result is showing wrong calculation so try to fix the bug.

For example weight 55 kg and height 180cm the result showing 15, but actual result 17 please check it.

![image](https://user-images.githubusercontent.com/52241455/101355032-0727fb80-38bc-11eb-9c6a-526e7c6452c7.png)

BMI =  body mass index
 m   =  mass (in kilograms)
 h    =  height (in meters)

**Comment by adpth** [comment]
Thank you for raising this issue, I have resolved it completely 🐞
